import type { DemoStep, DemoConfig } from "./interactive-demo";

export const PLATFORM_DEMO: DemoConfig = {
  name: "Content Rewards",
  steps: [
    {
      id: "sidebar",
      target: '[data-slot="sidebar-nav"]',
      title: "Your workspace sidebar",
      body: "Navigate everything from here — campaigns, creators, submissions, payouts, analytics, and more.",
      placement: "right",
      route: "/",
    },
    {
      id: "campaigns-nav",
      target: '[data-demo-nav="/campaigns"]',
      title: "Campaigns",
      body: "Create and manage marketing campaigns. Set budgets, define deliverables, and choose between CPM, retainer, or per-video models.",
      placement: "right",
      route: "/",
    },
    {
      id: "submissions-nav",
      target: '[data-demo-nav="/submissions"]',
      title: "Submissions",
      body: "When creators submit content, review it here. Approve, request changes, or reject — all in one place.",
      placement: "right",
      route: "/submissions",
    },
    {
      id: "creators-nav",
      target: '[data-demo-nav="/creators"]',
      title: "Creator network",
      body: "Browse your creator roster, view performance history, and manage relationships. Filter by platform or engagement rate.",
      placement: "right",
      route: "/creators",
    },
    {
      id: "contracts-nav",
      target: '[data-demo-nav="/contracts"]',
      title: "Contracts",
      body: "Manage all creator agreements — active, pending, expiring, and expired contracts in one place.",
      placement: "right",
      route: "/contracts",
    },
    {
      id: "new-contract",
      target: '[data-demo="new-contract"]',
      title: "Create a new contract",
      body: "Draft a new creator contract — choose the type, set terms, compensation, and deliverables.",
      placement: "bottom",
      route: "/contracts",
      actionLabel: "Try clicking this button",
    },
    {
      id: "payouts-nav",
      target: '[data-demo-nav="/payouts"]',
      title: "Payouts",
      body: "Track all creator payments — pending, completed, and clawed-back amounts with full audit trails.",
      placement: "right",
      route: "/payouts",
    },
    {
      id: "analytics-nav",
      target: '[data-demo-nav="/analytics"]',
      title: "Analytics",
      body: "Deep performance insights — views, engagement, conversions, and ROI across all campaigns.",
      placement: "right",
      route: "/analytics",
    },
    {
      id: "notifications-nav",
      target: '[data-demo-nav="/notifications"]',
      title: "Notifications",
      body: "All your alerts in one place — submissions, applications, payout updates, and budget warnings.",
      placement: "right",
      route: "/notifications",
    },
    {
      id: "notification-prefs",
      target: '[data-demo="notification-prefs"]',
      title: "Notification preferences",
      body: "Customize how and where you receive alerts — toggle channels like email, Slack, WhatsApp, and iMessage.",
      placement: "bottom",
      route: "/notifications",
      actionLabel: "Click to open preferences",
    },
    {
      id: "finish",
      target: '[data-demo-nav="/"]',
      title: "You're all set!",
      body: "That covers the key features. Explore at your own pace — everything is one click away from the sidebar.",
      placement: "right",
      route: "/",
    },
  ],
};

export const CREATOR_DEMO: DemoConfig = {
  name: "Creator Dashboard",
  steps: [
    {
      id: "creator-home",
      target: '[data-demo-nav="/creator"]',
      title: "Your creator home",
      body: "See active campaigns, upcoming deadlines, earnings summary, and personalized recommendations.",
      placement: "right",
      route: "/creator",
    },
    {
      id: "discover",
      target: '[data-demo-nav="/creator/discover"]',
      title: "Discover campaigns",
      body: "Browse all available campaigns. Filter by brand, payout model, platform, and category.",
      placement: "right",
      route: "/creator/discover",
    },
    {
      id: "creator-campaigns",
      target: '[data-demo-nav="/creator/campaigns"]',
      title: "Your campaigns",
      body: "Track campaigns you've joined — see deliverables, deadlines, and submission status.",
      placement: "right",
      route: "/creator/campaigns",
    },
    {
      id: "creator-submissions",
      target: '[data-demo-nav="/creator/submissions"]',
      title: "Your submissions",
      body: "Upload content and track review status. See approved, pending, and revision-requested submissions.",
      placement: "right",
      route: "/creator/submissions",
    },
    {
      id: "creator-payouts",
      target: '[data-demo-nav="/creator/payouts"]',
      title: "Your earnings",
      body: "View your complete earnings history and connect your preferred payment method.",
      placement: "right",
      route: "/creator/payouts",
    },
  ],
};
