import type {
  AlertItem,
  AlertRule,
  Campaign,
  Competitor,
  CreativeBrief,
  DetectedBrand,
  Post,
  SuggestedCompetitor,
  SwipeBoard,
  Theme,
} from "./types";

export const MOCK_WORKSPACE = {
  id: "ws_polymarket",
  name: "Polymarket",
  category: "Prediction markets / Crypto",
  brandUrl: "https://polymarket.com",
  logoUrl: "polymarket.com",
};

export const MOCK_COMPETITORS: Competitor[] = [
  {
    id: "c_kalshi",
    slug: "kalshi",
    name: "Kalshi",
    cat: "Prediction markets",
    logoUrl: "kalshi.com",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "kalshi", tt: "kalshi", yt: "kalshi" },
    followers: { ig: 412_000, tt: 189_000, yt: 44_200 },
    deltas: { ig: 2.1, tt: 8.9, yt: 1.2 },
    totalFollowers: 645_200,
    followerDeltaPct: 4.1,
    aggregate: {
      posts: 23,
      views: 4_200_000,
      eng: 5.8,
      engDelta: 1.2,
      velocity: 5,
      bestPlatform: "tt",
    },
  },
  {
    id: "c_manifold",
    slug: "manifold",
    name: "Manifold",
    cat: "Prediction markets",
    logoUrl: "manifold.markets",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "manifoldmarkets", tt: "manifold", yt: "manifoldmarkets" },
    followers: { ig: 68_400, tt: 94_200, yt: 12_100 },
    deltas: { ig: 0.8, tt: 3.4, yt: 2.7 },
    totalFollowers: 174_700,
    followerDeltaPct: 2.3,
    aggregate: {
      posts: 18,
      views: 890_000,
      eng: 4.1,
      engDelta: 0.4,
      velocity: 3,
      bestPlatform: "tt",
    },
  },
  {
    id: "c_drift",
    slug: "drift",
    name: "Drift",
    cat: "Perps DEX",
    logoUrl: "drift.trade",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "drifttrade", tt: "driftprotocol", yt: "drifttrade" },
    followers: { ig: 98_300, tt: 141_000, yt: 28_800 },
    deltas: { ig: 2.1, tt: 4.9, yt: 3.2 },
    totalFollowers: 268_100,
    followerDeltaPct: 3.4,
    aggregate: {
      posts: 31,
      views: 2_800_000,
      eng: 3.9,
      engDelta: -0.2,
      velocity: 4,
      bestPlatform: "yt",
    },
  },
  {
    id: "c_kaito",
    slug: "kaito",
    name: "Kaito",
    cat: "Crypto attention economy",
    logoUrl: "kaito.ai",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "kaito.ai", tt: "kaito.ai", yt: "kaito-ai" },
    followers: { ig: 52_400, tt: 118_800, yt: 8_600 },
    deltas: { ig: 6.7, tt: 11.4, yt: 4.9 },
    totalFollowers: 179_800,
    followerDeltaPct: 8.2,
    aggregate: {
      posts: 12,
      views: 6_100_000,
      eng: 7.2,
      engDelta: 2.8,
      velocity: 5,
      bestPlatform: "tt",
    },
  },
  {
    id: "c_predictit",
    slug: "predictit",
    name: "PredictIt",
    cat: "Political prediction markets",
    logoUrl: "predictit.org",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "predictit", tt: "predictit", yt: "predictitofficial" },
    followers: { ig: 34_200, tt: 21_900, yt: 6_800 },
    deltas: { ig: -0.3, tt: -0.1, yt: 0.4 },
    totalFollowers: 62_900,
    followerDeltaPct: -0.1,
    aggregate: {
      posts: 4,
      views: 64_000,
      eng: 1.8,
      engDelta: -0.6,
      velocity: 1,
      bestPlatform: "ig",
      down: true,
    },
  },
  {
    id: "c_zeta",
    slug: "zeta",
    name: "Zeta Markets",
    cat: "Solana options",
    logoUrl: "zeta.markets",
    platforms: ["ig", "tt", "yt"],
    handles: { ig: "zetamarkets", tt: "zetamarkets", yt: "zetamarkets" },
    followers: { ig: 18_900, tt: 41_200, yt: 5_400 },
    deltas: { ig: 1.2, tt: 5.8, yt: 2.9 },
    totalFollowers: 65_500,
    followerDeltaPct: 3.7,
    aggregate: {
      posts: 9,
      views: 420_000,
      eng: 3.2,
      engDelta: 0.9,
      velocity: 3,
      bestPlatform: "tt",
    },
  },
];

function p(partial: Omit<Post, "competitorLogoUrl"> & { logo?: string }): Post {
  return { ...partial, competitorLogoUrl: partial.logo ?? null };
}

export const MOCK_POSTS: Post[] = [
  p({
    id: "p_001",
    competitor: "Kalshi",
    logo: "kalshi.com",
    handle: "kalshi",
    platform: "tt",
    hours: 12,
    views: 2_320_000,
    likes: 94_100,
    comments: 1_240,
    velocity: 5,
    caption: "I turned $100 into $10K predicting the election — here's the exact account structure I used",
    hook: "I turned $X into $Y",
    format: "Talking head",
    duration: "0:48",
    url: "https://www.tiktok.com/@kalshi",
    thumbnailUrl: null,
  }),
  p({
    id: "p_002",
    competitor: "Manifold",
    logo: "manifold.markets",
    handle: "manifold",
    platform: "tt",
    hours: 8,
    views: 410_000,
    likes: 12_800,
    comments: 324,
    velocity: 4,
    caption: "What if everyone on Twitter bet on whether this tweet goes viral?",
    hook: "Question",
    format: "Meme/text",
    duration: "0:22",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_003",
    competitor: "Drift",
    logo: "drift.trade",
    handle: "drifttrade",
    platform: "yt",
    hours: 3,
    views: 180_000,
    likes: 4_900,
    comments: 210,
    velocity: 4,
    caption: "How I built a 10x leveraged SOL position in under 60 seconds",
    hook: "How I built",
    format: "Screen record",
    duration: "0:58",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_004",
    competitor: "Kaito",
    logo: "kaito.ai",
    handle: "kaito.ai",
    platform: "tt",
    hours: 6,
    views: 1_840_000,
    likes: 62_000,
    comments: 980,
    velocity: 5,
    caption: "Watch this creator earn $4,200 in a week just yapping about crypto on X",
    hook: "Watch this",
    format: "Talking head",
    duration: "0:41",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_005",
    competitor: "Kalshi",
    logo: "kalshi.com",
    handle: "kalshi",
    platform: "ig",
    hours: 18,
    views: 340_000,
    likes: 11_200,
    comments: 298,
    velocity: 3,
    caption: "We asked 100 traders: will SCOTUS rule before the election?",
    hook: "We asked",
    format: "Carousel",
    duration: undefined,
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_006",
    competitor: "Drift",
    logo: "drift.trade",
    handle: "driftprotocol",
    platform: "tt",
    hours: 14,
    views: 620_000,
    likes: 28_400,
    comments: 612,
    velocity: 4,
    caption: "POV: you found out about perps before your friends",
    hook: "POV",
    format: "Meme/text",
    duration: "0:17",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_007",
    competitor: "Manifold",
    logo: "manifold.markets",
    handle: "manifoldmarkets",
    platform: "yt",
    hours: 22,
    views: 94_000,
    likes: 3_100,
    comments: 198,
    velocity: 3,
    caption: "Market-making bots vs casual bettors — who wins over 6 months?",
    hook: "X vs Y",
    format: "Screen record",
    duration: "1:12",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_008",
    competitor: "Kaito",
    logo: "kaito.ai",
    handle: "kaito.ai",
    platform: "ig",
    hours: 11,
    views: 780_000,
    likes: 22_800,
    comments: 412,
    velocity: 4,
    caption: "The top 1% of creators made more than the bottom 80% combined this season",
    hook: "Statistic shock",
    format: "Carousel",
    duration: undefined,
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_009",
    competitor: "Zeta Markets",
    logo: "zeta.markets",
    handle: "zetamarkets",
    platform: "tt",
    hours: 5,
    views: 180_000,
    likes: 5_900,
    comments: 124,
    velocity: 3,
    caption: "Options 101: why gamma matters more than you think",
    hook: "Explainer",
    format: "Talking head",
    duration: "0:35",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_010",
    competitor: "PredictIt",
    logo: "predictit.org",
    handle: "predictit",
    platform: "ig",
    hours: 40,
    views: 28_000,
    likes: 640,
    comments: 54,
    velocity: 1,
    caption: "Markets moved on last night's debate — here's the 24h shift",
    hook: "News reaction",
    format: "Carousel",
    duration: undefined,
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_011",
    competitor: "Kalshi",
    logo: "kalshi.com",
    handle: "kalshi",
    platform: "yt",
    hours: 26,
    views: 540_000,
    likes: 18_900,
    comments: 412,
    velocity: 4,
    caption: "A retail trader turned $500 into $42K on a SCOTUS market — then lost it all",
    hook: "Cautionary tale",
    format: "Talking head",
    duration: "1:04",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_012",
    competitor: "Drift",
    logo: "drift.trade",
    handle: "drifttrade",
    platform: "ig",
    hours: 9,
    views: 210_000,
    likes: 6_800,
    comments: 188,
    velocity: 3,
    caption: "Perps liquidation stories from r/wallstreetbets, animated",
    hook: "Curated stories",
    format: "Carousel",
    duration: undefined,
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_013",
    competitor: "Manifold",
    logo: "manifold.markets",
    handle: "manifold",
    platform: "ig",
    hours: 30,
    views: 48_000,
    likes: 1_420,
    comments: 62,
    velocity: 2,
    caption: "The weirdest market on Manifold this week (it involves penguins)",
    hook: "Oddly specific",
    format: "Carousel",
    duration: undefined,
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_014",
    competitor: "Kaito",
    logo: "kaito.ai",
    handle: "kaito.ai",
    platform: "yt",
    hours: 20,
    views: 240_000,
    likes: 8_600,
    comments: 198,
    velocity: 4,
    caption: "Yap-to-Earn season 3 is live — here's the 3-tweet structure winning this week",
    hook: "Tutorial",
    format: "Screen record",
    duration: "0:52",
    url: null,
    thumbnailUrl: null,
  }),
  p({
    id: "p_015",
    competitor: "Zeta Markets",
    logo: "zeta.markets",
    handle: "zetamarkets",
    platform: "yt",
    hours: 36,
    views: 41_000,
    likes: 1_100,
    comments: 48,
    velocity: 2,
    caption: "How we built the fastest options matching engine on Solana",
    hook: "Behind the scenes",
    format: "Talking head",
    duration: "1:38",
    url: null,
    thumbnailUrl: null,
  }),
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "cam_001",
    host: "Kaito",
    name: "Yap-to-Earn S3",
    status: "new",
    launched: "2h ago",
    pool: 50_000,
    endsIn: "May 3",
    requirements: "3 tweets/week, must mention $KAITO in at least one",
    creators: 247,
    topEarning: "@whale_trader",
    source: "kaito.ai/leaderboard",
    desc: "Third season of Kaito's creator leaderboard. 50K pool split weekly by attention score.",
  },
  {
    id: "cam_002",
    host: "SideShift",
    name: "Trader Rewards",
    status: "active",
    launched: "8 days ago",
    pool: 42_000,
    endsIn: "10 days",
    requirements: "$10K+ swap volume + share a trade screenshot",
    creators: 240,
    topEarning: "@swapking",
    source: "sideshift.ai/announcements",
    desc: "Rewards for high-volume traders who post their trades publicly on X.",
  },
  {
    id: "cam_003",
    host: "Zealy",
    name: "Polymarket Clone Quest",
    status: "new",
    launched: "1 day ago",
    pool: 18_000,
    endsIn: "Apr 30",
    requirements: "Complete 5 quests, invite 3 friends",
    creators: 112,
    topEarning: null,
    source: "zealy.io/polymarket",
    desc: "Cross-platform quest inviting users to test a Polymarket-like interface on a new chain.",
  },
  {
    id: "cam_004",
    host: "Layer3",
    name: "Drift Perps Bootcamp",
    status: "active",
    launched: "5 days ago",
    pool: 25_000,
    endsIn: "14 days",
    requirements: "Complete 4 tutorial modules + post proof",
    creators: 880,
    topEarning: "@learnperps",
    source: "layer3.xyz/drift",
    desc: "Educational quest teaching perps basics via Drift Protocol.",
  },
  {
    id: "cam_005",
    host: "Galxe",
    name: "Manifold Forecast Arena",
    status: "ending",
    launched: "22 days ago",
    pool: 12_000,
    endsIn: "2 days",
    requirements: "Create 10 markets, resolve 5 correctly",
    creators: 64,
    topEarning: "@goodforecaster",
    source: "galxe.com/manifold",
    desc: "Forecasting accuracy competition on Manifold's real-money markets.",
  },
  {
    id: "cam_006",
    host: "Kaito",
    name: "Mindshare Winter Cup",
    status: "active",
    launched: "11 days ago",
    pool: 30_000,
    endsIn: "18 days",
    requirements: "Top 50 in mindshare score for 2 consecutive weeks",
    creators: 412,
    topEarning: "@mindshare_maxi",
    source: "kaito.ai/announcements",
    desc: "Long-form winter season run through Kaito's attention leaderboard.",
  },
  {
    id: "cam_007",
    host: "SideShift",
    name: "Creator Referrals",
    status: "ending",
    launched: "28 days ago",
    pool: 8_500,
    endsIn: "4 days",
    requirements: "Refer a trader who swaps >$5K",
    creators: 48,
    topEarning: "@swapqueen",
    source: "sideshift.ai/referrals",
    desc: "Affiliate-style referrals for high-value traders on SideShift.",
  },
  {
    id: "cam_008",
    host: "Zealy",
    name: "Kalshi Election Hub",
    status: "new",
    launched: "6h ago",
    pool: 22_000,
    endsIn: "May 12",
    requirements: "Share election markets insight + create a Kalshi account",
    creators: 78,
    topEarning: null,
    source: "zealy.io/kalshi",
    desc: "Cross-promo quest driving signups to Kalshi's election markets hub.",
  },
];

export const MOCK_THEMES: Theme[] = [
  { rank: 1, name: "2024 election predictions", count: 23, deltaPct: 48, trend: [4, 7, 6, 9, 12, 14, 16, 22, 24] },
  { rank: 2, name: "X payout screenshots", count: 18, deltaPct: 32, trend: [2, 3, 4, 6, 8, 10, 13, 16, 18] },
  { rank: 3, name: "Bet tracker tutorials", count: 14, deltaPct: 21, trend: [5, 6, 7, 8, 9, 11, 12, 13, 14] },
  { rank: 4, name: "Perps liquidation stories", count: 11, deltaPct: 18, trend: [2, 4, 5, 6, 8, 9, 10, 11, 11] },
  { rank: 5, name: "Solana options deep dives", count: 8, deltaPct: 12, trend: [1, 2, 3, 4, 5, 6, 7, 8, 8] },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "a_001",
    kind: "campaign",
    title: "Kaito launched Yap-to-Earn S3",
    body: "$50K pool, 3 tweets/week requirement. 247 creators already participating.",
    ago: "2h ago",
    action: "View campaign",
  },
  {
    id: "a_002",
    kind: "viral",
    title: "Kalshi TikTok hit 1M views in 6h",
    body: "\"I turned $100 into $10K predicting the election\" is at 2.3M views and climbing.",
    ago: "5h ago",
    action: "Watch",
  },
  {
    id: "a_003",
    kind: "campaign",
    title: "Zealy quest mentions Polymarket by name",
    body: "A new quest at zealy.io/polymarket-clone is driving signups to a competing platform.",
    ago: "1d ago",
    action: "Review",
  },
  {
    id: "a_004",
    kind: "theme",
    title: "\"Payout screenshots\" is trending across your competitors",
    body: "18 posts this week from 4 competitors use payout screenshots as the hook.",
    ago: "1d ago",
    action: "Explore",
  },
  {
    id: "a_005",
    kind: "viral",
    title: "Kaito IG post crossed 700K views",
    body: "Creator-rewards recap carousel hit 780K views and 22K likes in under 12h.",
    ago: "1d ago",
    action: "Watch",
  },
  {
    id: "a_006",
    kind: "campaign",
    title: "Galxe / Manifold quest ending in 2 days",
    body: "Forecast Arena quest wraps Friday. 64 creators are participating.",
    ago: "2d ago",
    action: "View campaign",
  },
];

export const MOCK_ALERT_RULES: AlertRule[] = [
  {
    id: "r_campaign",
    type: "campaign",
    label: "New campaign launches",
    description: "Ping me whenever a competitor launches a creator, affiliate, or rewards program.",
    enabled: true,
    focusCompetitor: null,
    channels: { email: true, slack: true, discord: false, telegram: false },
  },
  {
    id: "r_viral",
    type: "viral",
    label: "Viral competitor post",
    description: "Fire when a tracked post crosses 500K views within 24h of posting.",
    enabled: true,
    focusCompetitor: "Kalshi",
    channels: { email: true, slack: false, discord: true, telegram: false },
  },
  {
    id: "r_digest",
    type: "digest",
    label: "Daily digest",
    description: "Every morning at 9am ET: top 5 posts + any new campaigns from the last 24h.",
    enabled: false,
    focusCompetitor: null,
    channels: { email: true, slack: false, discord: false, telegram: false },
  },
];

export const MOCK_SWIPE_BOARDS: SwipeBoard[] = [
  {
    id: "b_hooks",
    name: "Hooks that work",
    itemCount: 4,
    items: MOCK_POSTS.slice(0, 4),
  },
  {
    id: "b_q2",
    name: "Q2 inspiration",
    itemCount: 6,
    items: MOCK_POSTS.slice(2, 8),
  },
  {
    id: "b_th",
    name: "Talking-head formats",
    itemCount: 3,
    items: MOCK_POSTS.filter((post) => post.format === "Talking head").slice(0, 3),
  },
];

export const MOCK_BRIEF: CreativeBrief = {
  title: "Turn receipts into proof: payout screenshots as the hook",
  angle:
    "Adapt Kaito's winning carousel format by leading with a raw earnings screenshot — then reverse-engineer the strategy for Polymarket's creator tier.",
  audience: "Crypto-native retail traders, 22–35, already posting on X",
  hook: "Show the screenshot first. Everything else earns the scroll.",
  structure: [
    "Open on a full-bleed earnings screenshot (blurred handle if needed).",
    "Caption: \"$4,200 in a week. Here's the actual strategy.\"",
    "Beat 1: what markets they traded (2 specific examples).",
    "Beat 2: the copy-paste tweet format they used.",
    "Beat 3: the tier-unlock moment and the exact CTA.",
  ],
  doThis: [
    "Use real, unretouched screenshots — authenticity reads instantly.",
    "Name two specific markets or tickers in the first 5 seconds.",
    "End on a single, crisp CTA to join the Polymarket creator tier.",
  ],
  avoidThis: [
    "Don't hide the numbers behind a clickbait caption — audiences bounce.",
    "Avoid generic \"I made $X\" openers that competitors have saturated.",
    "Don't gate the strategy behind a newsletter signup in-feed.",
  ],
  cta: "Open Polymarket → Creator tier",
};

export const MOCK_DETECTED_BRAND: DetectedBrand = {
  name: "Polymarket",
  url: "https://polymarket.com",
  category: "Prediction markets / Crypto",
  description:
    "The world's largest prediction market. Trade on news, politics, and more with real money on Ethereum.",
  logoUrl: "polymarket.com",
  socials: { ig: "polymarket", tt: "polymarket", yt: "polymarketofficial" },
};

export const MOCK_SUGGESTED_COMPETITORS: SuggestedCompetitor[] = [
  { name: "Kalshi", url: "https://kalshi.com", handles: { instagram: "kalshi", tiktok: "kalshi", youtube: "kalshi" }, rationale: "CFTC-regulated, largest direct competitor for US election markets.", logoUrl: "kalshi.com" },
  { name: "Manifold", url: "https://manifold.markets", handles: { instagram: "manifoldmarkets", tiktok: "manifold", youtube: "manifoldmarkets" }, rationale: "Crowd-powered play-money markets, strongest in forecasting community.", logoUrl: "manifold.markets" },
  { name: "Drift", url: "https://drift.trade", handles: { instagram: "drifttrade", tiktok: "driftprotocol", youtube: "drifttrade" }, rationale: "Closest adjacent on trading creator content — perps not markets, but the audience overlaps hard.", logoUrl: "drift.trade" },
  { name: "Kaito", url: "https://kaito.ai", handles: { instagram: "kaito.ai", tiktok: "kaito.ai", youtube: "kaito-ai" }, rationale: "Competes on attention-economy creator programs — the exact space we want to watch.", logoUrl: "kaito.ai" },
  { name: "PredictIt", url: "https://predictit.org", handles: { instagram: "predictit", tiktok: "predictit", youtube: "predictitofficial" }, rationale: "Legacy political prediction market — historically dominant but now shrinking.", logoUrl: "predictit.org" },
  { name: "Zeta Markets", url: "https://zeta.markets", handles: { instagram: "zetamarkets", tiktok: "zetamarkets", youtube: "zetamarkets" }, rationale: "Adjacent on Solana DeFi; interesting for format benchmarking even if user overlap is smaller.", logoUrl: "zeta.markets" },
  { name: "Limitless", url: "https://limitless.exchange", handles: { instagram: "limitlesslabs", tiktok: "limitlessexchange", youtube: "limitlessexchange" }, rationale: "New on-chain prediction entrant targeting US retail.", logoUrl: "limitless.exchange" },
  { name: "Myriad Markets", url: "https://myriad.markets", handles: { instagram: "myriadmarkets", tiktok: "myriadmarkets", youtube: "myriadmarkets" }, rationale: "Decrypt-backed prediction markets, strong in media verticals.", logoUrl: "myriad.markets" },
];
